-- AlterTable
ALTER TABLE `permission` MODIFY `name` ENUM('CREATE_USER', 'READ_USERS', 'UPDATE_USER', 'DELETE_USER', 'READ_PROFILE', 'CREATE_ITEM', 'READ_ITEMS', 'UPDATE_ITEM', 'DELETE_ITEM', 'WB_FFB_REUPLOAD', 'WB_SPLIT_SO', 'WB_CP_UPDATE', 'WB_BARGE_UPDATE', 'WB_SQL_EXECUTE') NOT NULL;
